[package]
name = "sqlx-test-example"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT"

[dependencies]
sqlx = { version = "0.7.3", features = ["runtime-tokio", "postgres"] }

[workspace]
